// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZtCYQXt5wNMp1N1kS0oRMotJhs26vaL4',
    appId: '1:292197273646:web:e8cc2486bae2af9fb88fbf',
    messagingSenderId: '292197273646',
    projectId: 'ownapinews',
    authDomain: 'ownapinews.firebaseapp.com',
    storageBucket: 'ownapinews.appspot.com',
    measurementId: 'G-QGKGRGZY8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD16wTB8iP5FoXdruZ5lLnwfJ4cMxzE0Iw',
    appId: '1:292197273646:android:af3e655e1b2572d2b88fbf',
    messagingSenderId: '292197273646',
    projectId: 'ownapinews',
    storageBucket: 'ownapinews.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3PR1hBO8Vlhrz6crb4FmOwE8uuv40xXY',
    appId: '1:292197273646:ios:956f41454815b22ab88fbf',
    messagingSenderId: '292197273646',
    projectId: 'ownapinews',
    storageBucket: 'ownapinews.appspot.com',
    iosBundleId: 'com.example.newsOwnapi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3PR1hBO8Vlhrz6crb4FmOwE8uuv40xXY',
    appId: '1:292197273646:ios:956f41454815b22ab88fbf',
    messagingSenderId: '292197273646',
    projectId: 'ownapinews',
    storageBucket: 'ownapinews.appspot.com',
    iosBundleId: 'com.example.newsOwnapi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZtCYQXt5wNMp1N1kS0oRMotJhs26vaL4',
    appId: '1:292197273646:web:35746162e88954c4b88fbf',
    messagingSenderId: '292197273646',
    projectId: 'ownapinews',
    authDomain: 'ownapinews.firebaseapp.com',
    storageBucket: 'ownapinews.appspot.com',
    measurementId: 'G-YWWXM1YZN6',
  );
}
